import type { Review, ReviewAggregate } from './types';

export const mockReviews: Review[] = [
  {
    id: 'fb-sarah-charlie',
    source: 'facebook_manual',
    isPublished: true,
    isFeatured: true,
    authorName: 'Sarah W.',
    authorLocation: 'Huntsville, AL',
    rating: 5,
    body: 'We picked up Charlie in June and he has been the sweetest, healthiest puppy. Communication was excellent and every vet record was ready at pickup.',
    headline: 'Healthiest pup we have owned',
    visitDate: '2025-06-18',
    photoUrl: '/reviews/sarah-charlie.webp',
    sourceUrl: 'https://facebook.com/review/sarah-charlie',
    createdAt: '2025-06-19T14:00:00.000Z',
    updatedAt: '2025-06-19T14:00:00.000Z',
  },
  {
    id: 'fb-mark-lisa-duke',
    source: 'facebook_manual',
    isPublished: true,
    isFeatured: true,
    authorName: 'Mark & Lisa P.',
    authorLocation: 'Birmingham, AL',
    rating: 5,
    body: 'Deposit and pickup were fast and professional. Duke came home socialized, mostly potty trained, and our vet loved his condition.',
    headline: 'Pickup was effortless',
    visitDate: '2025-07-03',
    photoUrl: '/reviews/mark-lisa-duke.webp',
    sourceUrl: 'https://facebook.com/review/mark-lisa-duke',
    createdAt: '2025-07-04T10:00:00.000Z',
    updatedAt: '2025-07-04T10:00:00.000Z',
  },
  {
    id: 'fb-anthony-tommy',
    source: 'facebook_manual',
    isPublished: true,
    isFeatured: true,
    authorName: 'Anthony D.',
    authorLocation: 'Montgomery, AL',
    rating: 5,
    body: 'Top-notch breeder. You can tell the dogs are loved - Tommy settled in immediately and has the funniest personality.',
    headline: 'Truly care for their dogs',
    visitDate: '2025-05-27',
    photoUrl: '/reviews/anthony-tommy.webp',
    sourceUrl: 'https://facebook.com/review/anthony-tommy',
    createdAt: '2025-05-28T09:00:00.000Z',
    updatedAt: '2025-05-28T09:00:00.000Z',
  },
  {
    id: 'manual-rachel-ga',
    source: 'manual',
    isPublished: true,
    isFeatured: true,
    authorName: 'Rachel K.',
    authorLocation: 'Atlanta, GA',
    rating: 5,
    body: 'Worth the drive from Georgia. The health guarantee and updates before pickup made the whole experience feel premium.',
    headline: 'Worth the drive',
    visitDate: '2025-07-22',
    photoUrl: null,
    sourceUrl: null,
    createdAt: '2025-07-23T11:30:00.000Z',
    updatedAt: '2025-07-23T11:30:00.000Z',
  },
  {
    id: 'manual-cameron-milo',
    source: 'manual',
    isPublished: true,
    isFeatured: false,
    authorName: 'Cameron H.',
    authorLocation: 'Decatur, AL',
    rating: 5,
    body: 'PayPal checkout was simple and Milo is already the star of the neighborhood. They shared quick videos during the wait.',
    headline: 'Smooth checkout',
    visitDate: '2025-09-05',
    photoUrl: '/reviews/cameron-milo.webp',
    sourceUrl: null,
    createdAt: '2025-09-06T16:00:00.000Z',
    updatedAt: '2025-09-06T16:00:00.000Z',
  },
  {
    id: 'manual-taylor-atl',
    source: 'manual',
    isPublished: true,
    isFeatured: false,
    authorName: 'Taylor R.',
    authorLocation: 'Atlanta, GA',
    rating: 4,
    body: 'Great communication and coordination for delivery. Appreciated the health packet when we picked up Luna.',
    headline: 'Great coordination',
    visitDate: '2025-09-12',
    photoUrl: null,
    sourceUrl: null,
    createdAt: '2025-09-13T12:00:00.000Z',
    updatedAt: '2025-09-13T12:00:00.000Z',
  },
  {
    id: 'manual-pending-james',
    source: 'manual',
    isPublished: false,
    isFeatured: false,
    authorName: 'James L.',
    authorLocation: 'Chattanooga, TN',
    rating: 5,
    body: 'Left our visit feeling confident. Loved how they let the kids interact with the litter and answered every question.',
    headline: 'Fantastic visit',
    visitDate: '2025-09-20',
    photoUrl: null,
    sourceUrl: null,
    createdAt: '2025-09-21T09:30:00.000Z',
    updatedAt: '2025-09-21T09:30:00.000Z',
  },
  {
    id: 'fb-featured-natalie',
    source: 'facebook_manual',
    isPublished: true,
    isFeatured: true,
    authorName: 'Natalie C.',
    authorLocation: 'Mobile, AL',
    rating: 5,
    body: 'We adopted our second bulldog from EBL. Both puppies came home healthy and social. Payment and pickup were simple.',
    headline: 'Second bulldog from EBL',
    visitDate: '2025-08-15',
    photoUrl: '/reviews/mark-lisa-duke.webp',
    sourceUrl: 'https://facebook.com/review/natalie-mobile',
    createdAt: '2025-08-16T08:00:00.000Z',
    updatedAt: '2025-08-16T08:00:00.000Z',
  },
];

export const mockPublishedReviews = mockReviews.filter((review) => review.isPublished);

export const mockFeaturedReviews = mockPublishedReviews
  .filter((review) => review.isFeatured)
  .slice(0, 10);

export function computeAggregate(reviews: Review[]): ReviewAggregate {
  if (reviews.length === 0) {
    return { averageRating: 0, reviewCount: 0 };
  }

  const total = reviews.reduce((sum, review) => sum + review.rating, 0);
  return {
    averageRating: parseFloat((total / reviews.length).toFixed(1)),
    reviewCount: reviews.length,
  };
}
